### ISSUE TITLE
Why use this over stylelint-config-html?

### ISSUE THREAD

**Issue by vuolter** [mattpfeffer/stylelint-config-astro#4]
As written in the README itself, this package leverages [stylelint-config-html](https://github.com/ota-meshi/stylelint-config-html), 
so I wonder why someone would use this instead of stylelint-config-html, what are its advantages?

Thank you.

**Comment by mattpfeffer** [comment]
At the time of release, stylelint-config-html didn't play well with .astro files. So i created this fork (although it wasn't strictly a fork). It does look like they have since added support but I haven't tested that myself. In time I may deprecate this project in favour of that one.
